import React from 'react'
import {Table} from 'react-bootstrap'

const Standings = () => {
  return (
    <div class="logos1">
    <tbody>
    <tr class="standings__tableHeader">
    <th>#</th> 
    <th>Club</th> 
    <th class="standings__value">GS</th> 
    <th class="standings__value">W</th> 
    <th class="standings__value">G</th>
    <th class="standings__value">V</th> 
    <th class="standings__value standings__goalScoredAndConceded">DV-DT</th>
     <th class="standings__value">DS</th> <th class="standings__value">Pt.</th></tr> 
     <tr class=""><td>1</td>
      <td class="standings__teamColumn">
      <div>
      <img src="https://www.feyenoord.nl/-/media/images/logos/clubs/_0019_nl-ajax.png?as=0&amp;mh=200&amp;mw=200&amp;hash=D0915ED7479B8606737FE195A4A1F20E37769281" alt="Ajax logo" height="50" class="standings__teamLogo"/>
      </div> <strong class="standings__teamName">Ajax</strong></td> 
      <td class="standings__value">29</td>
       <td class="standings__value">23</td> <td class="standings__value">3</td> 
       <td class="standings__value">3</td> <td class="standings__value standings__goalScoredAndConceded">85-15</td>
        <td class="standings__value">70</td> <td class="standings__value"><strong>72</strong></td></tr><tr class=""><td>2</td> 
        <td class="standings__teamColumn"><div><img src="https://www.feyenoord.nl/-/media/images/logos/clubs/_0007_nl-psv.png?as=0&amp;mh=200&amp;mw=200&amp;hash=D99454EEC8EDBD40D76BCAABE0188A184049881B" alt="PSV logo" height="50" class="standings__teamLogo"/>
        </div> <strong class="standings__teamName">PSV</strong></td> <td class="standings__value">29</td> <td class="standings__value">22</td> <td class="standings__value">2</td> <td class="standings__value">5</td> <td class="standings__value standings__goalScoredAndConceded">73-34</td> <td class="standings__value">39</td> <td class="standings__value"><strong>68</strong></td></tr><tr class="standingsByLeague__isFeyenoord"><td>3</td> <td class="standings__teamColumn"><div><img src="https://www.feyenoord.nl/-/media/images/logos/clubs/_0012_nl-feyenoord.png?as=0&amp;mh=200&amp;mw=200&amp;hash=AD61616C2AF13F807A7639BDF0B796D74F1BC8B4" alt="Feyenoord logo" height="50" class="standings__teamLogo"/></div> <strong class="standings__teamName">Feyenoord</strong></td> <td class="standings__value">29</td> <td class="standings__value">19</td> <td class="standings__value">4</td> <td class="standings__value">6</td> <td class="standings__value standings__goalScoredAndConceded">67-28</td> <td class="standings__value">39</td> <td class="standings__value"><strong>61</strong></td></tr><tr class="">
        <td>4</td> <td class="standings__teamColumn"><div><img src="https://www.feyenoord.nl/-/media/images/logos/clubs/logo-fc-twente-1.png?as=0&amp;mh=200&amp;mw=200&amp;hash=C1D9EBFA3995E12C303D5D1B7B4BDCE10F9E3810" alt="FC Twente logo" height="50" class="standings__teamLogo"/></div> <strong class="standings__teamName">FC Twente</strong></td> <td class="standings__value">29</td> <td class="standings__value">17</td> <td class="standings__value">7</td> <td class="standings__value">5</td> <td class="standings__value standings__goalScoredAndConceded">46-33</td> <td class="standings__value">13</td> <td class="standings__value"><strong>58</strong></td></tr><tr class=""><td>5</td> <td class="standings__teamColumn"><div><img src="https://www.feyenoord.nl/-/media/images/logos/clubs/az_200x200.png?as=0&amp;mh=200&amp;mw=200&amp;hash=E02A5F9477A436AEB1FD896E40E9A7DA53E46A5F" alt="AZ logo" height="50" class="standings__teamLogo"/></div> <strong class="standings__teamName">AZ</strong></td> <td class="standings__value">29</td> <td class="standings__value">17</td> <td class="standings__value">4</td> <td class="standings__value">8</td> <td class="standings__value standings__goalScoredAndConceded">56-35</td> <td class="standings__value">21</td> <td class="standings__value"><strong>55</strong></td></tr><tr class=""><td>6</td> <td class="standings__teamColumn"><div>
            <img src="https://www.feyenoord.nl/-/media/images/logos/clubs/_0005_nl-vitesse.png?as=0&amp;mh=200&amp;mw=200&amp;hash=E0DB86E941CC3A2EE1BAD15180D1299797F61602" alt="Vitesse logo" height="50" class="standings__teamLogo"/>
        </div> <strong class="standings__teamName">Vitesse</strong></td> <td class="standings__value">28</td> <td class="standings__value">13</td> <td class="standings__value">5</td> <td class="standings__value">10</td> <td class="standings__value standings__goalScoredAndConceded">35-43</td> <td class="standings__value">-8</td> <td class="standings__value"><strong>44</strong></td></tr><tr class=""><td>7</td> <td class="standings__teamColumn"><div><img src="https://www.feyenoord.nl/-/media/0-nieuwsberichten/20212022/08-augustus/fc-utrecht-logo-png-2021-2022.png?as=0&amp;mh=200&amp;mw=200&amp;hash=DF4A7F689DBB11132DF84A033DEC899B8BBD2C62" alt="FC Utrecht logo" height="50" class="standings__"/></div> <strong class="standings__teamName">FC Utrecht</strong></td> <td class="standings__value">29</td> <td class="standings__value">11</td> <td class="standings__value">9</td> <td class="standings__value">9</td> <td class="standings__value standings__goalScoredAndConceded">46-38</td> <td class="standings__value">8</td> <td class="standings__value"><strong>42</strong></td></tr><tr class=""><td>8</td> <td class="standings__teamColumn"><div><img src="https://www.feyenoord.nl/-/media/images/logos/clubs/groningen_200x200.png?as=0&amp;mh=200&amp;mw=200&amp;hash=12B3DD550865951CD924301B039872FBF886830C" alt="FC Groningen logo" height="50" class="standings__teamLogo"/>
        </div> <strong class="standings__teamName">FC Groningen</strong></td> <td class="standings__value">29</td> <td class="standings__value">9</td> <td class="standings__value">9</td> <td class="standings__value">11</td> <td class="standings__value standings__goalScoredAndConceded">37-43</td> <td class="standings__value">-6</td> <td class="standings__value"><strong>36</strong></td></tr><tr class=""><td>9</td> <td class="standings__teamColumn"><div><img src="https://www.feyenoord.nl/-/media/images/logos/clubs/_0002_nl-go-ahead-eagles.png?as=0&amp;mh=200&amp;mw=200&amp;hash=CC6B3B36CC8C37EFD0704370C3F180B6BC9404EF" alt="Go Ahead Eagles logo" height="50" class="standings__teamLogo"/>
        </div> <strong class="standings__teamName">Go Ahead Eagles</strong></td> <td class="standings__value">29</td> <td class="standings__value">10</td> <td class="standings__value">6</td> <td class="standings__value">13</td> <td class="standings__value standings__goalScoredAndConceded">35-43</td> <td class="standings__value">-8</td> <td class="standings__value"><strong>36</strong></td></tr><tr class=""><td>10</td> <td class="standings__teamColumn"><div><img src="https://www.feyenoord.nl/-/media/images/logos/clubs/_0000_nl-nec-nijmegen.png?as=0&amp;mh=200&amp;mw=200&amp;hash=C6C3C8A5E727360A957ED5858F0EAE235042B77D" alt="NEC logo" height="50" class="standings__teamLogo"/>
        </div> <strong class="standings__teamName">NEC</strong></td> <td class="standings__value">29</td> <td class="standings__value">9</td> <td class="standings__value">8</td> <td class="standings__value">12</td> <td class="standings__value standings__goalScoredAndConceded">35-46</td> <td class="standings__value">-11</td> <td class="standings__value"><strong>35</strong></td></tr><tr class=""><td>11</td> <td class="standings__teamColumn"><div><img src="https://www.feyenoord.nl/-/media/images/logos/clubs/heerenveen_200x200.png?as=0&amp;mh=200&amp;mw=200&amp;hash=9C00452666F248AC27F6B23D7FD1302DC5DBB042" alt="SC Heerenveen logo" height="50" class="standings__teamLogo"/>
        </div> <strong class="standings__teamName">SC Heerenveen</strong></td> <td class="standings__value">29</td> <td class="standings__value">9</td> <td class="standings__value">7</td> <td class="standings__value">13</td> <td class="standings__value standings__goalScoredAndConceded">28-38</td> <td class="standings__value">-10</td> <td class="standings__value"><strong>34</strong></td></tr><tr class=""><td>12</td> <td class="standings__teamColumn"><div><img src="https://www.feyenoord.nl/-/media/images/logos/clubs/sc-cambuur.png?as=0&amp;mh=200&amp;mw=200&amp;hash=158EC3D56081AA480E76B29ECF4CF699A1B938F6" alt="SC Cambuur logo" height="50" class="standings__teamLogo"/>
        </div> <strong class="standings__teamName">SC Cambuur</strong></td> <td class="standings__value">29</td> <td class="standings__value">10</td> <td class="standings__value">3</td> <td class="standings__value">16</td> <td class="standings__value standings__goalScoredAndConceded">44-61</td> <td class="standings__value">-17</td> <td class="standings__value"><strong>33</strong></td></tr><tr class=""><td>13</td> <td class="standings__teamColumn"><div><img src="https://www.feyenoord.nl/-/media/images/logos/clubs/_0010_nl-heracles.png?as=0&amp;mh=200&amp;mw=200&amp;hash=8EACC1FAC9ABAC8C05D1AD3F250F69DFA9C28F9F" alt="Heracles Almelo logo" height="50" class="standings__teamLogo"/>
        </div> <strong class="standings__teamName">Heracles Almelo</strong></td> <td class="standings__value">29</td> <td class="standings__value">8</td> <td class="standings__value">6</td> <td class="standings__value">15</td> <td class="standings__value standings__goalScoredAndConceded">30-41</td> <td class="standings__value">-11</td> <td class="standings__value"><strong>30</strong></td></tr><tr class=""><td>14</td> <td class="standings__teamColumn"><div><img src="https://www.feyenoord.nl/-/media/0-nieuwsberichten/20192020/08-augustus/rkc-waalwijk---met-witruimte-goed---1920.png?as=0&amp;mh=200&amp;mw=200&amp;hash=60628CB5C0CF423803C34C15795BE0F8BA992595" alt="RKC Waalwijk logo" height="50" class="standings__teamLogo"/
        ></div> <strong class="standings__teamName">RKC Waalwijk</strong></td> <td class="standings__value">29</td> <td class="standings__value">6</td> <td class="standings__value">10</td> <td class="standings__value">13</td> <td class="standings__value standings__goalScoredAndConceded">31-46</td> <td class="standings__value">-15</td> <td class="standings__value"><strong>28</strong></td></tr><tr class=""><td>15</td> <td class="standings__teamColumn"><div><img src="https://www.feyenoord.nl/-/media/images/logos/clubs/_0008_nl-pec-zwolle.png?as=0&amp;mh=200&amp;mw=200&amp;hash=0FE960257D7FC0F5B949FBF5D3F4A05FA4BADC17" alt="PEC Zwolle logo"  height="50" class="standings__teamLogo"/>
        </div> <strong class="standings__teamName">PEC Zwolle</strong></td> <td class="standings__value">29</td> <td class="standings__value">6</td> <td class="standings__value">5</td> <td class="standings__value">18</td> <td class="standings__value standings__goalScoredAndConceded">22-44</td> <td class="standings__value">-22</td> <td class="standings__value"><strong>23</strong></td></tr><tr class=""><td>16</td> <td class="standings__teamColumn"><div><img src="https://www.feyenoord.nl/-/media/images/logos/clubs/willem-ii_200x200.png?as=0&amp;mh=200&amp;mw=200&amp;hash=0DCF41561676F5E752022AB89D19E255FD61229D" alt="Willem II logo" height="50" class="standings__teamLogo"/>
        </div> <strong class="standings__teamName">Willem II</strong></td> <td class="standings__value">29</td> <td class="standings__value">6</td> <td class="standings__value">5</td> <td class="standings__value">18</td> <td class="standings__value standings__goalScoredAndConceded">23-52</td> <td class="standings__value">-29</td> <td class="standings__value"><strong>23</strong></td></tr><tr class=""><td>17</td> <td class="standings__teamColumn"><div><img src="https://www.feyenoord.nl/-/media/images/logos/clubs/_0011_nl-fortuna-sittard.png?as=0&amp;mh=200&amp;mw=200&amp;hash=D58D80C63C2D1B87BFEEF6C2E88EA7A3C2882C07" alt="Fortuna Sittard logo" height="50" class="standings__teamLogo"/></div> <strong class="standings__teamName">Fortuna Sittard</strong></td> <td class="standings__value">28</td> <td class="standings__value">6</td> <td class="standings__value">5</td> <td class="standings__value">17</td> <td class="standings__value standings__goalScoredAndConceded">27-61</td> <td class="standings__value">-34</td> <td class="standings__value"><strong>23</strong></td></tr><tr class=""><td>18</td> <td class="standings__teamColumn"><div><img src="https://www.feyenoord.nl/-/media/images/logos/clubs/_0003_nl-sparta.png?as=0&amp;mh=200&amp;mw=200&amp;hash=8914816DEAE3133BEC86811123473BCA7C5059E1" alt="Sparta Rotterdam logo" height="50" class="standings__teamLogo"/></div> <strong class="standings__teamName">Sparta Rotterdam</strong></td> <td class="standings__value">27</td> <td class="standings__value">4</td> <td class="standings__value">10</td> <td class="standings__value">13</td> <td class="standings__value standings__goalScoredAndConceded">21-40</td> <td class="standings__value">-19</td> <td class="standings__value"><strong>22</strong></td></tr></tbody>
     
     <div>
         
     </div>
        
        </div>
  )
}

export default Standings